install:
  - ps: Start-FileDownload 'http://downloads.dlang.org/releases/2.x/2.076.0/dmd.2.076.0.windows.7z' -FileName 'dmd2.7z'
  - 7z x dmd2.7z > nul
  - set PATH=%CD%\dmd2\windows\bin;%CD%\dmd2\windows\bin64;%PATH%
  - dmd.exe --version
  - dub.exe --version
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - dub test --arch=x86_64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - set DFLAGS=-m32mscoff
  - dub test --arch=x86
